version: '3'

x-environment: &environment
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_HOST: ${MYSQL_HOST}
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  DATABASE_URL: ${DATABASE_URL}
  TZ: 'Asia/Tokyo'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql_container
    environment: *environment
    volumes:
      - ./backend/docker/mysql/data:/var/lib/mysql
      - ./backend/docker/mysqk/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./backend/docker/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-net
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  backend:
    build: backend/
    environment: *environment
    container_name: kakeibo-backend
    networks:
      - app-net
    ports:
      - "8080:8080"

  frontend:
    build: frontend/
    container_name: kakeibo-frontend
    networks:
      - app-net
    ports:
      - "3000:3000"
    command: yarn start
  
networks:
  app-net:
    driver: bridge