CREATE TABLE IF NOT EXISTS money_transactions (
    id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "主キー",
    destination VARCHAR(256) NOT NULL COMMENT "支払い先",
    source VARCHAR(256) NOT NULL COMMENT "支払い元",
    amount INT(15) NOT NULL COMMENT "金額",
    nominal VARCHAR(128) NOT NULL COMMENT "名目",
    description VARCHAR(512) NOT NULL COMMENT "説明",
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT "登録日",
    update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新日"
    );
CREATE TABLE IF NOT EXISTS transaction_suppliers (
    id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT "ID",
    supplier VARCHAR(256) NOT NULL COMMENT "売買主",
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT "登録日",
    update_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "更新日"
    );